apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  labels:
    zone: dev
    version: v1
spec:
  containers:
  - name: hello-ctr
    image: asakchris/spring-boot-docker:latest
    ports:
    - containerPort: 8080
