apiVersion: v1
kind: ReplicationController
metadata: 
  name: hello-rc
spec:
  replicas: 4
  selector:
    app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-pod
        image: asakchris/spring-boot-docker:latest
        ports:
        - containerPort: 8080
